sudo: required
dist: trusty
language: c
compiler: gcc
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y autoconf build-essential libjson-c2 libjson-c-dev libunistring0 libunistring-dev
  - autoreconf -i -s
